version: '3'

services:
  db:
    image: mysql:8.0
    container_name: "djangodb_v1"
    ports: 
        - "3306:3306"
    security_opt:
      - seccomp:unconfined
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: django_database
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test 
    volumes:
        - ./api/dump:/docker-entrypoint-initdb.d
        - ./api/conf:/etc/mysql/conf.d
        - ./api/persistent:/var/lib/mysql
    networks:
      django-net:

  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      django-net:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "djangophp_v1"
    links: 
        - db:db
    ports:
        - 8001:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test 
    networks:
      django-net:

  frontend: 
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      django-net:

volumes:
  node-modules:

networks:
  django-net:
